import './globals.css'
import { Montserrat } from 'next/font/google'
import Nav from "@/components/Nav"
import Footer from "@/components/Footer"

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
